### ISSUE TITLE
Reporting wrong click operation while clicking on links

### ISSUE THREAD

**Issue by Jawasri** [PratheeshAnbu99/OpenGoogle-_Code#7]
Dear Anbu,
I have faced a wrong click on a link while running the code.

**Comment by PratheeshAnbu99** [comment]
Hi Jawasri,
Thanks for mentioned this bug soon it will be resolved. Thanks for mentioning and sorry for your inconvenience.

**Comment by PratheeshAnbu99** [comment]
Dear JawaSri,
thanks for your patience .we have fixed the bug now you can work without any issues.
